apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-order
  name: ms-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-order
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-order
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: pubsub-key
      containers:
        - image: gcr.io/learning-357114/ms-order:1.0.0
          name: ms-order
          resources: {}
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
              protocol: TCP
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: ms-order
  name: ms-order
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3333
      protocol: TCP
      targetPort: 3333
  selector:
    app: ms-order
  type: ClusterIP
